library("RMySQL")
library("plotly")
library("dplyr")
library("RecordLinkage")

correct_cities <- 
  c("Thane",
    "Calicut",
    "North 24 Parganas",
    "Bangalore",
    "Pune",
    "Mumbai",
    "South 24 Parganas",
    "Bardhaman",
    "Ahmedabad",
    "Murshidabad",
    "Jaipur",
    "Nashik",
    "Allahabad",
    "Patna",
    "Hooghly",
    "Ranga Reddy",
    "Nadia",
    "East Godavari",
    "Paschim Medinipur",
    "East Champaran",
    "Surat",
    "Guntur",
    "Howrah",
    "Muzaffarpur",
    "Belgaum",
    "Moradabad",
    "Chennai",
    "Ghaziabad",
    "Nagpur",
    "Azamgarh",
    "Lucknow",
    "Kanpur Nagar",
    "Ahmednagar",
    "Krishna",
    "Kolkata",
    "Jaunpur district",
    "Madhubani",
    "Sitapur",
    "Bareilly",
    "Gorakhpur",
    "Purba Medinipur",
    "Agra",
    "Gaya",
    "Solapur",
    "Visakhapatnam",
    "Samastipur",
    "Jalgaon",
    "Chittoor",
    "Muzaffarnagar",
    "Malappuram",
    "Hardoi",
    "Anantapur",
    "Raipur",
    "Kurnool",
    "Mahbubnagar",
    "Lakhimpur Kheri",
    "Hyderabad",
    "Maldah",
    "Madurai",
    "Kanchipuram",
    "Saran",
    "West Champaran",
    "West Godavari",
    "Vellore",
    "Darbhanga",
    "Kolhapur",
    "Jalpaiguri",
    "Karimnagar",
    "Sultanpur",
    "Tiruvallur",
    "Budaun",
    "Aurangabad",
    "Jodhpur",
    "Bijnor",
    "Varanasi",
    "Aligarh",
    "Alwar",
    "North West Delhi",
    "Vadodara",
    "Ghazipur",
    "Bankura",
    "Kushinagar",
    "Warangal",
    "Ganjam",
    "Birbhum",
    "Bulandshahr",
    "Vaishali",
    "Ludhiana",
    "Nalgonda",
    "Salem",
    "Coimbatore",
    "Saharanpur",
    "Viluppuram",
    "Meerut",
    "Gonda",
    "Sitamarhi",
    "Raebareli",
    "Prakasam",
    "Nanded",
    "Durg",
    "Siwan",
    "Nagaur",
    "Thiruvananthapuram",
    "Ernakulam",
    "Purnia",
    "Indore",
    "Barabanki",
    "Ballia",
    "Pratapgarh",
    "Rajkot",
    "Mumbai City",
    "Banaskantha",
    "Unnao",
    "Thrissur",
    "Deoria",
    "Kozhikode",
    "Tirunelveli",
    "Katihar",
    "Udaipur",
    "Bhagalpur",
    "Medak",
    "Satara",
    "Shahjahanpur",
    "Uttar Dinajpur",
    "Mysore",
    "Sri Potti Sriramulu Nellore",
    "Rohtas",
    "Begusarai",
    "Purulia",
    "Ranchi",
    "Patiala",
    "Amravati",
    "Kadapa",
    "Bhavnagar",
    "Nalanda",
    "Kanyakumari",
    "Nagaon",
    "Cooch Behar",
    "Sangli",
    "Palakkad",
    "Araria",
    "Khammam",
    "Yavatmal",
    "Junagadh",
    "Adilabad",
    "South Delhi",
    "Bhojpur",
    "Tiruchirappalli",
    "Srikakulam",
    "Dhanbad",
    "Tumkur",
    "Sikar",
    "Maharajganj",
    "Bilaspur",
    "Raigad",
    "Fatehpur",
    "Kollam",
    "Cuttack",
    "Barmer",
    "Cuddalore",
    "Buldhana",
    "Beed",
    "Ajmer",
    "Gulbarga",
    "Gopalganj",
    "Siddharthnagar",
    "Nizamabad",
    "Bharatpur",
    "Mathura",
    "Bellary",
    "West Delhi",
    "Kannur",
    "Mayurbhanj",
    "Aurangabad",
    "Firozabad",
    "Mirzapur",
    "Amritsar",
    "Tirupur",
    "Tiruvannamalai",
    "Faizabad",
    "Basti",
    "Jabalpur",
    "Latur",
    "Giridih",
    "Sabarkantha",
    "Bhilwara",
    "Thanjavur",
    "Ambedkar Nagar",
    "Panchmahal",
    "Bahraich",
    "Sagar",
    "Bhopal",
    "Bikaner",
    "Rewa",
    "Vizianagaram",
    "Rampur",
    "Balasore",
    "Gurdaspur",
    "Kheda",
    "South West Delhi",
    "East Singhbhum",
    "Erode",
    "Khordha",
    "North East Delhi",
    "Satna",
    "Supaul",
    "Sambhal(Bheem Nagar)",
    "Nawada",
    "Mau",
    "Chandrapur",
    "Dhar",
    "Jalandhar",
    "Vijayapura",
    "Dindigul",
    "Jamnagar",
    "Balrampur",
    "Jhunjhunu",
    "Dahod",
    "Alappuzha",
    "Kutch",
    "Chhindwara",
    "Anand",
    "Dakshina Kannada",
    "Sundargarh",
    "Bokaro",
    "Dhule",
    "Churu",
    "Pali",
    "Pilibhit",
    "Gwalior",
    "Banka",
    "Mehsana",
    "Firozpur",
    "Jhansi",
    "Pathankot",
    "Madhepura",
    "Ujjain",
    "Kottayam",
    "Ganganagar",
    "Morena",
    "Jalna",
    "Chandauli",
    "Kota",
    "Dhubri",
    "Davanagere",
    "Virudhunagar",
    "Palamu",
    "Haridwar",
    "Sonitpur",
    "Raichur",
    "Pudukkottai",
    "Saharsa",
    "Bagalkot",
    "Farrukhabad",
    "Krishnagiri",
    "Khargone (West Nimar)",
    "Sonbhadra",
    "Mainpuri",
    "Dharwad",
    "Darjeeling",
    "Jyotiba Phule Nagar",
    "Parbhani",
    "Jalore",
    "Jajpur",
    "Akola",
    "Mandya",
    "Kendujhar (Keonjhar)",
    "Banda",
    "Faridabad",
    "Banswara",
    "Kanpur Dehat (Ramabai Nagar)",
    "Hanumangarh",
    "Hassan",
    "Chhatarpur",
    "Etah",
    "Jamui",
    "Surendranagar",
    "Shimoga",
    "Hissar",
    "Thoothukudi",
    "Cachar",
    "Hazaribag",
    "Shivpuri",
    "Namakkal",
    "Sant Kabir Nagar",
    "East Delhi",
    "Buxar",
    "Bhind",
    "Valsad",
    "Balaghat",
    "Bidar",
    "Alipurduar",
    "Dehradun",
    "Puri",
    "Barpeta",
    "Kishanganj",
    "Gautam Buddh Nagar",
    "Dakshin Dinajpur",
    "Jalaun",
    "Chitradurga",
    "Osmanabad",
    "Kannauj",
    "Khagaria",
    "Sangrur",
    "Balangir",
    "Udham Singh Nagar",
    "Nandurbar",
    "Dausa",
    "Bhiwani",
    "Kaimur",
    "Janjgir-Champa",
    "Nagapattinam",
    "Ratnagiri",
    "Haveri district",
    "Kaushambi",
    "Hoshiarpur",
    "Etawah",
    "Betul",
    "Kalahandi",
    "Hathras (Mahamaya Nagar)",
    "Dewas",
    "Sant Ravidas Nagar",
    "Bharuch",
    "Rajgarh",
    "Chittorgarh",
    "Kolar",
    "Rajnandgaon",
    "Jammu",
    "Kamrup",
    "Gurgaon",
    "Amreli district",
    "Shajapur",
    "Kangra",
    "Bhadrak",
    "Karnal",
    "Dharmapuri",
    "West Singhbhum",
    "Raigarh",
    "Deoghar",
    "Sonipat",
    "Bargarh (Baragarh)",
    "Karauli",
    "Vidisha",
    "Ratlam",
    "Hapur (Panchsheel Nagar)",
    "Tikamgarh",
    "Kendrapara",
    "Kanshi Ram Nagar",
    "Tonk",
    "Bastar",
    "Jhalawar",
    "Koppal",
    "Dungapur",
    "Bathinda",
    "Gandhinagar",
    "Barwani",
    "Seoni",
    "Koraput",
    "Auraiya",
    "Munger",
    "Uttara Kannada",
    "Patan",
    "Sivaganga",
    "Mandsaur",
    "Sawai Madhopur",
    "Ramanathapuram",
    "Jind",
    "Raisen",
    "Navsari",
    "Dibrugarh",
    "Garhwa",
    "Gondia",
    "Dumka",
    "Tinsukia",
    "Godda",
    "Sehore",
    "Khandwa (East Nimar)",
    "Kasaragod",
    "Bagpat",
    "Wardha",
    "Sirsa",
    "Katni",
    "Angul",
    "Srinagar",
    "Tiruvarur",
    "Damoh",
    "Kamrup Metropolitan",
    "Chikkaballapur",
    "Theni",
    "Hoshangabad",
    "Guna",
    "Baran",
    "Nabarangpur",
    "Lalitpur",
    "Gir Somnath",
    "Karimganj",
    "Yamuna Nagar",
    "Dholpur",
    "Korba",
    "Panipat",
    "Bhandara",
    "Washim",
    "Pathanamthitta",
    "Dhenkanal",
    "Hingoli",
    "Singrauli",
    "Udupi",
    "Yadgir",
    "Rajsamand",
    "Sivasagar",
    "Sahibganj",
    "Chikkamagaluru",
    "Ambala",
    "Jagatsinghpur",
    "Sidhi",
    "Jehanabad",
    "Tarn Taran",
    "Shravasti",
    "Bundi",
    "Idukki",
    "Hamirpur",
    "Narsinghpur",
    "Jorhat",
    "Mewat",
    "Ramanagara",
    "Karur",
    "Kaithal",
    "Chhota Udaipur",
    "Gadchiroli",
    "Anantnag",
    "Gadag",
    "Shahdol",
    "Seraikela Kharsawan",
    "Rohtak",
    "Golaghat",
    "Chandigarh",
    "Mandla",
    "Aravalli",
    "Sambalpur",
    "Chatra",
    "Lakhimpur",
    "Palwal",
    "Sirohi",
    "Mahasamund",
    "Gumla",
    "Jhabua",
    "Chamarajnagar",
    "Panna",
    "Baramulla",
    "Goalpara",
    "Lakhisarai",
    "Mandi",
    "Mahisagar",
    "Moga",
    "Chitrakoot",
    "Bangalore Rural",
    "Sahibzada Ajit Singh Nagar",
    "Karbi Anglong",
    "Kurukshetra",
    "Nayagarh",
    "Rayagada",
    "Morbi",
    "Morigaon",
    "Jhajjar",
    "Nainital",
    "Baksa",
    "Ramgarh",
    "Pondicherry",
    "Fatehabad",
    "Mahendragarh",
    "West Tripura",
    "Darrang",
    "Sri Muktsar Sahib",
    "Pakur",
    "Rewari",
    "Kokrajhar",
    "North Delhi",
    "Mahoba",
    "Kupwara",
    "Pratapgarh",
    "Jashpur",
    "Sindhudurg",
    "Ashok Nagar",
    "Udalguri",
    "Neemuch",
    "East Khasi Hills",
    "North Goa",
    "Kapurthala",
    "Wayanad",
    "Shimla",
    "Tapi",
    "Dhamtari",
    "Jamtara",
    "Datia",
    "Nalbari",
    "Mansa",
    "Burhanpur",
    "Devbhoomi Dwarka",
    "Ariyalur",
    "Anuppur",
    "Kanker",
    "Badgam",
    "Nilgiris",
    "Bongaigaon",
    "Kandhamal",
    "Alirajpur",
    "Latehar",
    "Koderma",
    "Dindori",
    "Arwal",
    "Dhemaji",
    "Sheopur",
    "Pauri Garhwal",
    "Rupnagar",
    "Jaisalmer",
    "Surajpur",
    "Hailakandi",
    "Koriya",
    "Sheohar",
    "Botad",
    "Subarnapur (Sonepur)",
    "Umaria",
    "West Garo Hills",
    "South Goa",
    "Sheikhpura",
    "Almora",
    "Rajouri",
    "Faridkot",
    "Tehri Garhwal",
    "Kathua",
    "Shahid Bhagat Singh Nagar",
    "Malkangiri",
    "Nuapada",
    "Fatehgarh Sahib",
    "Simdega",
    "Barnala",
    "Narmada",
    "Porbandar",
    "Kabirdham (formerly Kawardha)",
    "Jharsuguda",
    "Central Delhi",
    "Solan",
    "Gajapati",
    "Harda",
    "Pulwama",
    "Perambalur",
    "Panchkula",
    "Udhampur",
    "Kodagu",
    "Dantewada",
    "Khunti",
    "Sirmaur",
    "Una",
    "Chamba",
    "Imphal West",
    "Pithoragarh",
    "Sepahijala",
    "Chirang",
    "Poonch",
    "Lohardaga",
    "Hamirpur",
    "Imphal East",
    "Boudh (Bauda)",
    "Kullu",
    "Gomati",
    "South Tripura",
    "Kulgam",
    "Surguja",
    "Thoubal",
    "North Tripura",
    "Tuensang",
    "Doda",
    "Aizawl",
    "Chamoli",
    "West Khasi Hills",
    "Bandipora",
    "Bilaspur",
    "Dimapur",
    "Dhalai",
    "Senapati",
    "Dadra and Nagar Haveli",
    "Uttarkashi",
    "Khowai",
    "Samba",
    "East Garo Hills",
    "Reasi",
    "Debagarh (Deogarh)",
    "Ganderbal",
    "Ramban",
    "East Sikkim",
    "Unokoti",
    "Churachandpur",
    "West Jaintia Hills",
    "Kohima",
    "Shopian",
    "Bageshwar",
    "Mon",
    "Champawat",
    "Ri Bhoi",
    "Bijapur",
    "Sukma",
    "Bishnupur",
    "South Andaman",
    "Rudraprayag",
    "Kishtwar",
    "Dang",
    "Dima Hasao",
    "Karaikal",
    "Mokokchung",
    "Daman",
    "Ukhrul",
    "Papum Pare",
    "Wokha",
    "Peren",
    "Phek",
    "Lunglei",
    "Changlang",
    "Leh",
    "South Sikkim",
    "Lohit",
    "Chandel",
    "Kargil",
    "South Garo Hills",
    "Zunheboto",
    "Narayanpur",
    "Tamenglong",
    "West Sikkim",
    "New Delhi",
    "Champhai",
    "East Jaintia Hills",
    "North Garo Hills",
    "Lawngtlai",
    "West Siang",
    "Tirap",
    "South West Khasi Hills",
    "North and Middle Andaman",
    "East Siang",
    "Kurung Kumey",
    "West Kameng",
    "Mamit",
    "Kinnaur",
    "Upper Subansiri",
    "Kolasib",
    "Lower Subansiri",
    "East Kameng",
    "Kiphire",
    "Serchhip",
    "Lakshadweep",
    "Saiha",
    "Yanam",
    "Lower Dibang Valley",
    "Diu",
    "Longleng",
    "Tawang",
    "North Sikkim",
    "Mahe",
    "Nicobar",
    "Upper Siang",
    "Lahaul and Spiti",
    "Anjaw",
    "Dibang Valley",
    "Fazilka",
    "Shamli",
    "Balrampur",
    "Bemetara",
    "Palghar",
    "Longding",
    "Balod",
    "Baloda Bazar",
    "Gariaband",
    "Kondagaon",
    "Mungeli",
    "Shahdara",
    "South East Delhi",
    "Agar",
    "South West Garo Hills",
    "Amethi")

# Connection to MySQL
ElephantiasisAnalysis <- dbConnect(MySQL(), user='root', password='hello', dbname='ElephantiasisAnalysis', host='localhost')

# Table of contacts of patients
patient_contact <- dbGetQuery(ElephantiasisAnalysis, "select * from contact;")

# Table of limb data
limb_data <- dbGetQuery(ElephantiasisAnalysis, "select * from limb_data_revised;")

# Table of volume change
limb_volume_change <- dbGetQuery(ElephantiasisAnalysis, "select * from limb_vol_change;")

# List to store correctly spelled cities
actual_cities <- c()

count <- 0
similarity <- 0
correct_city <- ""
k <- 1

patient_contact2 <- patient_contact

patient_contact2 <- patient_contact2[complete.cases(patient_contact2[, "city"]), ]

# Loop to correct city spellings
for(i in 1:nrow(patient_contact2)){
  max_similarity <- -99
  for(j in 1:length(correct_cities)) {
    similarity <- jarowinkler(correct_cities[j], patient_contact2[i, "city"])
    if(TRUE &&(similarity>max_similarity)) {
      max_similarity = similarity
      correct_city <- correct_cities[j]
    }
  }
  patient_contact2[i, "city"] <- tolower(correct_city)
}

# Consider only districs that appear over 5 times
patient_contact2 <- patient_contact2[patient_contact2$city %in% names(table(patient_contact2$city))[table(patient_contact2$city) >= 10],]

# List of unique districts
unique_cities <- unique(patient_contact2$city)

names(patient_contact2)[1] = "patient_limb_id"
limb_data_revised <- merge(limb_data, patient_contact2, by = "patient_limb_id")
limb_data_revised <- merge(limb_data_revised, limb_volume_change, by = c("patient_limb_id", "followup_code"))
limb_data_revised <- limb_data_revised[, c("patient_limb_id", "affected_nonaffected_limb", "followup_code", "city", "vol_change")]

# Average volume change per district
avg <- list()
ctr <- 1
colors <- c("red", "blue", "yellow", "purple", "green", "orange", "black")

num_affected <- data.frame("District" = "None", "Number_Affected" = 0)
num_affected <- num_affected[-c(1), ]

for(i in unique_cities){
  set <- subset(limb_data_revised, city == i)
  add_row <- data.frame("State" = i, "Number_Affected" = length(unique(set$patient_limb_id)))
  num_affected <- rbind(num_affected, add_row)
  
  avg[[i]] <- data.frame("followup_no" = c(1, 2, 3, 4, 5, 6), "avg_change" = 0, "count" = 0)
  
  for(j in 1:nrow(set)){
    avg[[i]]$avg_change[set$followup_code[j]] <- avg[[i]]$avg_change[set$followup_code[j]] + set$vol_change[j]
    avg[[i]]$count[set$followup_code[j]] <- avg[[i]]$count[set$followup_code[j]] + 1
  }
  
  for(j in 1:6){
    avg[[i]]$avg_change[j] <- avg[[i]]$avg_change[j]/avg[[i]]$count[j]
  }
  
  avg[[i]]$avg_change[1] <- 0

}

num_affected <- num_affected[order(-num_affected$Number_Affected), ]

 for(i in c(1:6)){
  plot(x = avg[[num_affected$State[i]]]$followup_no, y = avg[[num_affected$State[i]]]$avg_change, type = "o", main = "District Wise Change in Volume vs Followups", xlab = "Followup Code", ylab = "Volume Change", col = colors[ctr], ylim = c(-1.0, 2.0), lwd = 1)
  par(new = TRUE)
  ctr <- ctr + 1
}
legend("topright",legend = num_affected$State[1:6], col = colors, lwd = 2, cex = 0.75)

barplot(num_affected$Number_Affected[1:5], names.arg = num_affected$State[1:5], main="Distribution of Patients", xlab="Districts", ylab="No. of Patients")

# Close the connection with MySQL
list <- dbListConnections(MySQL())
for(con in list) {
  dbDisconnect(con)
}

